"""
Automated follow-ups (run by the in-process scheduler — app/services/scheduler.py).

Two jobs:
  - run_appointment_reminders(): nudges patients before upcoming appointments
    (24h and 2h windows), once per window, marking app.reminders so it never
    double-sends.
  - run_reengagement(): re-engages contacts who went silent (last_inbound_at older
    than REENGAGE_AFTER_DAYS) and aren't converted/blocked/paused, throttled by
    REENGAGE_COOLDOWN_DAYS. Message text is generated by Sofia.

Both respect a per-tenant opt-out in settings.followups and require a connected
WhatsApp instance. Every send is wrapped so one failure can't abort the batch.
Outbound messages are persisted so they appear in the inbox.
"""

import logging
from datetime import datetime, timedelta, timezone

from sqlalchemy import or_, select

from app.config import settings
from app.database import AsyncSessionLocal
from app.models.appointment import Appointment, AppointmentStatus
from app.models.contact import Contact, ContactStatus, CrmStage
from app.models.message import Message, MessageChannel, MessageDirection
from app.models.tenant import Tenant
from app.services import ai as ai_service
from app.services import whatsapp as wa_service
from app.services.ai_tools import _clinic_tz, _fmt_local

logger = logging.getLogger(__name__)

# Default hours-before windows for appointment reminders (largest first).
_DEFAULT_REMINDER_WINDOWS = [24, 2]
# Upper bound on how far ahead we look for reminders (caps per-clinic config).
_MAX_REMINDER_HORIZON_HOURS = 72


def _tenant_instance(tenant: Tenant) -> str | None:
    """The clinic's UAZAPI instance token (auth for outbound sends), or None."""
    return (tenant.settings or {}).get("whatsapp", {}).get("token")


def _followups_cfg(tenant: Tenant) -> dict:
    return (tenant.settings or {}).get("followups", {}) or {}


def _reminder_windows(tenant: Tenant) -> list[int]:
    """Per-clinic reminder windows (hours before), validated + sorted desc.
    Falls back to the default when unset/invalid."""
    raw = _followups_cfg(tenant).get("reminder_hours")
    if isinstance(raw, list) and raw:
        valid: list[int] = []
        for h in raw:
            try:
                v = int(h)
            except (TypeError, ValueError):
                continue
            if 0 < v <= _MAX_REMINDER_HORIZON_HOURS:
                valid.append(v)
        if valid:
            return sorted(set(valid), reverse=True)
    return sorted(_DEFAULT_REMINDER_WINDOWS, reverse=True)


async def _save_outbound(db, tenant_id, contact_id, text: str) -> None:
    db.add(Message(
        tenant_id=tenant_id,
        contact_id=contact_id,
        direction=MessageDirection.OUTBOUND,
        channel=MessageChannel.WHATSAPP,
        content=text,
        ai_model_used="sofia-followup",
    ))


async def run_appointment_reminders() -> None:
    now = datetime.now(timezone.utc)
    horizon = now + timedelta(hours=_MAX_REMINDER_HORIZON_HOURS)

    async with AsyncSessionLocal() as db:
        appts = (
            await db.execute(
                select(Appointment).where(
                    Appointment.status.in_([AppointmentStatus.SCHEDULED, AppointmentStatus.CONFIRMED]),
                    Appointment.scheduled_at > now,
                    Appointment.scheduled_at <= horizon,
                )
            )
        ).scalars().all()

        tenant_cache: dict = {}
        sent = 0
        for appt in appts:
            tenant = tenant_cache.get(appt.tenant_id) or await db.get(Tenant, appt.tenant_id)
            tenant_cache[appt.tenant_id] = tenant
            if tenant is None:
                continue
            instance = _tenant_instance(tenant)
            if not instance or _followups_cfg(tenant).get("reminders_enabled", True) is False:
                continue

            windows = _reminder_windows(tenant)  # per-clinic, sorted desc
            hours_until = (appt.scheduled_at - now).total_seconds() / 3600
            reminders = dict(appt.reminders or {})

            for i, w in enumerate(windows):
                lower = windows[i + 1] if i + 1 < len(windows) else 0
                if lower < hours_until <= w and str(w) not in reminders:
                    contact = await db.get(Contact, appt.contact_id)
                    if not contact or not contact.phone:
                        break
                    tz = _clinic_tz(tenant.settings or {})
                    when = _fmt_local(appt.scheduled_at, tz)
                    text = (
                        f"Olá, {contact.full_name}! 😊 Passando para lembrar do seu "
                        f"agendamento na {tenant.name}: {when}. Posso confirmar a sua presença?"
                    )
                    try:
                        await wa_service.send_text_message(instance_token=instance, phone=contact.phone, text=text)
                    except Exception:
                        logger.exception("reminder_send_failed", extra={"appointment_id": str(appt.id)})
                        break
                    reminders[str(w)] = now.isoformat()
                    appt.reminders = reminders
                    await _save_outbound(db, appt.tenant_id, appt.contact_id, text)
                    sent += 1
                    break

        await db.commit()
        if sent:
            logger.info("appointment_reminders_sent", extra={"count": sent})


def _int_cfg(cfg: dict, key: str, default: int) -> int:
    try:
        return int(cfg.get(key, default))
    except (TypeError, ValueError):
        return default


async def run_reengagement() -> None:
    now = datetime.now(timezone.utc)

    async with AsyncSessionLocal() as db:
        tenants = (
            await db.execute(select(Tenant).where(Tenant.is_active.is_(True)))
        ).scalars().all()

        total = 0
        for tenant in tenants:
            instance = _tenant_instance(tenant)
            fcfg = _followups_cfg(tenant)
            if not instance or fcfg.get("reengagement_enabled", True) is False:
                continue

            # Per-clinic timing (falls back to global defaults).
            after_days = max(1, _int_cfg(fcfg, "reengage_after_days", settings.REENGAGE_AFTER_DAYS))
            cooldown_days = max(1, _int_cfg(fcfg, "reengage_cooldown_days", settings.REENGAGE_COOLDOWN_DAYS))
            silent_before = now - timedelta(days=after_days)
            cooldown_before = now - timedelta(days=cooldown_days)

            contacts = (
                await db.execute(
                    select(Contact).where(
                        Contact.tenant_id == tenant.id,
                        Contact.last_inbound_at.is_not(None),
                        Contact.last_inbound_at < silent_before,
                        Contact.crm_stage.in_([
                            CrmStage.NEW_LEAD.value,
                            CrmStage.COLD_LEAD.value,
                            CrmStage.HOT_LEAD.value,
                        ]),
                        Contact.status != ContactStatus.BLOCKED,
                        Contact.ai_paused.is_(False),
                        or_(Contact.last_followup_at.is_(None), Contact.last_followup_at < cooldown_before),
                    ).limit(20)
                )
            ).scalars().all()

            for contact in contacts:
                if not contact.phone:
                    continue
                message = await ai_service.generate_followup_message(tenant, contact)
                if not message:
                    continue
                try:
                    await wa_service.send_text_message(instance_token=instance, phone=contact.phone, text=message)
                except Exception:
                    logger.exception("reengagement_send_failed", extra={"contact_id": str(contact.id)})
                    continue
                contact.last_followup_at = now
                await _save_outbound(db, tenant.id, contact.id, message)
                total += 1

        await db.commit()
        if total:
            logger.info("reengagement_sent", extra={"count": total})
