"""
Automated follow-ups (run by the in-process scheduler — app/services/scheduler.py).

Three jobs:
  - run_appointment_reminders(): nudges patients before upcoming appointments
    (24h and 2h windows), once per window, marking app.reminders so it never
    double-sends. Text is picked from a set of natural-sounding variations
    (see _REMINDER_TEMPLATES) so a patient getting 2+ reminders never sees the
    exact same wording twice.
  - run_reengagement(): re-engages contacts who went silent (last_inbound_at older
    than REENGAGE_AFTER_DAYS) and aren't converted/blocked/paused, throttled by
    REENGAGE_COOLDOWN_DAYS. Message text is generated by Sofia, grounded in the
    contact's recent conversation history when there's one worth referencing.
  - run_paused_alert(): a second-layer alert for contacts handed off to a human
    (ai_paused=True) whose last message is still an unanswered inbound one,
    older than HANDOFF_ALERT_STALE_MINUTES — i.e. nobody picked it up. Emails
    the clinic once per pause "episode" (see the function docstring for how
    episodes are tracked without a dedicated reset elsewhere in the code).

All three respect a per-tenant opt-out in settings.followups and require a
connected WhatsApp instance (run_paused_alert only needs the email channel).
Every send is wrapped so one failure can't abort the batch. Outbound WhatsApp
messages are persisted so they appear in the inbox.
"""

import logging
import random
from datetime import datetime, timedelta, timezone

from sqlalchemy import or_, select

from app.config import settings
from app.database import AsyncSessionLocal
from app.models.appointment import Appointment, AppointmentStatus
from app.models.contact import Contact, ContactStatus, CrmStage
from app.models.message import Message, MessageChannel, MessageDirection
from app.models.tenant import Tenant
from app.services import ai as ai_service
from app.services import whatsapp as wa_service
from app.services.ai_tools import _clinic_tz, _fmt_local
from app.services.alerts import send_handoff_alert_email

logger = logging.getLogger(__name__)

# Default hours-before windows for appointment reminders (largest first).
_DEFAULT_REMINDER_WINDOWS = [24, 2]
# Upper bound on how far ahead we look for reminders (caps per-clinic config).
_MAX_REMINDER_HORIZON_HOURS = 72

# 3.4 — several warm, natural-sounding variations of the same reminder so a
# patient who gets 2+ reminders over time (e.g. the 24h + 2h windows) never
# sees the exact same sentence twice — that repetition is what tips patients
# off that they're talking to a script instead of a person. All variations
# carry the same facts (name, clinic, when) and never invent anything else.
_REMINDER_TEMPLATES = [
    "Olá, {name}! 😊 Passando para lembrar do seu agendamento na {clinic}: {when}. Posso confirmar a sua presença?",
    "Oi, {name}! Tudo bem? Só um lembrete rapidinho do seu horário na {clinic}, marcado para {when}. Posso contar com você? 💛",
    "{name}, bom dia! Vim avisar que seu horário na {clinic} está chegando: {when}. Confirma pra mim que vai dar certo?",
    "Ei, {name}! Passando aqui pra lembrar do seu compromisso na {clinic}, em {when}. Tudo certo pra esse horário?",
    "Oi {name} 🙂 Seu atendimento na {clinic} está agendado para {when} — posso deixar confirmado?",
    "{name}, olha só: seu horário na {clinic} é {when}. Consigo confirmar sua presença?",
]


def _reminder_text(name: str, clinic: str, when: str) -> str:
    """Pick a random reminder wording. Pure function (no I/O) — easy to call
    repeatedly from a test to check the templates actually vary."""
    template = random.choice(_REMINDER_TEMPLATES)
    return template.format(name=name, clinic=clinic, when=when)


def _tenant_instance(tenant: Tenant) -> str | None:
    """The clinic's UAZAPI instance token (auth for outbound sends), or None."""
    return (tenant.settings or {}).get("whatsapp", {}).get("token")


def _followups_cfg(tenant: Tenant) -> dict:
    return (tenant.settings or {}).get("followups", {}) or {}


def _reminder_windows(tenant: Tenant) -> list[int]:
    """Per-clinic reminder windows (hours before), validated + sorted desc.
    Falls back to the default when unset/invalid."""
    raw = _followups_cfg(tenant).get("reminder_hours")
    if isinstance(raw, list) and raw:
        valid: list[int] = []
        for h in raw:
            try:
                v = int(h)
            except (TypeError, ValueError):
                continue
            if 0 < v <= _MAX_REMINDER_HORIZON_HOURS:
                valid.append(v)
        if valid:
            return sorted(set(valid), reverse=True)
    return sorted(_DEFAULT_REMINDER_WINDOWS, reverse=True)


async def _save_outbound(db, tenant_id, contact_id, text: str) -> None:
    db.add(Message(
        tenant_id=tenant_id,
        contact_id=contact_id,
        direction=MessageDirection.OUTBOUND,
        channel=MessageChannel.WHATSAPP,
        content=text,
        ai_model_used="sofia-followup",
    ))


async def run_appointment_reminders() -> None:
    now = datetime.now(timezone.utc)
    horizon = now + timedelta(hours=_MAX_REMINDER_HORIZON_HOURS)

    async with AsyncSessionLocal() as db:
        appts = (
            await db.execute(
                select(Appointment).where(
                    Appointment.status.in_([AppointmentStatus.SCHEDULED, AppointmentStatus.CONFIRMED]),
                    Appointment.scheduled_at > now,
                    Appointment.scheduled_at <= horizon,
                )
            )
        ).scalars().all()

        tenant_cache: dict = {}
        sent = 0
        for appt in appts:
            tenant = tenant_cache.get(appt.tenant_id) or await db.get(Tenant, appt.tenant_id)
            tenant_cache[appt.tenant_id] = tenant
            if tenant is None:
                continue
            instance = _tenant_instance(tenant)
            if not instance or _followups_cfg(tenant).get("reminders_enabled", True) is False:
                continue

            windows = _reminder_windows(tenant)  # per-clinic, sorted desc
            hours_until = (appt.scheduled_at - now).total_seconds() / 3600
            reminders = dict(appt.reminders or {})

            for i, w in enumerate(windows):
                lower = windows[i + 1] if i + 1 < len(windows) else 0
                if lower < hours_until <= w and str(w) not in reminders:
                    contact = await db.get(Contact, appt.contact_id)
                    if not contact or not contact.phone:
                        break
                    tz = _clinic_tz(tenant.settings or {})
                    when = _fmt_local(appt.scheduled_at, tz)
                    text = _reminder_text(contact.full_name, tenant.name, when)
                    try:
                        await wa_service.send_text_message(instance_token=instance, phone=contact.phone, text=text)
                    except Exception:
                        logger.exception("reminder_send_failed", extra={"appointment_id": str(appt.id)})
                        break
                    reminders[str(w)] = now.isoformat()
                    appt.reminders = reminders
                    await _save_outbound(db, appt.tenant_id, appt.contact_id, text)
                    sent += 1
                    break

        await db.commit()
        if sent:
            logger.info("appointment_reminders_sent", extra={"count": sent})


def _int_cfg(cfg: dict, key: str, default: int) -> int:
    try:
        return int(cfg.get(key, default))
    except (TypeError, ValueError):
        return default


async def run_reengagement() -> None:
    now = datetime.now(timezone.utc)

    async with AsyncSessionLocal() as db:
        tenants = (
            await db.execute(select(Tenant).where(Tenant.is_active.is_(True)))
        ).scalars().all()

        total = 0
        for tenant in tenants:
            instance = _tenant_instance(tenant)
            fcfg = _followups_cfg(tenant)
            if not instance or fcfg.get("reengagement_enabled", True) is False:
                continue

            # Per-clinic timing (falls back to global defaults).
            after_days = max(1, _int_cfg(fcfg, "reengage_after_days", settings.REENGAGE_AFTER_DAYS))
            cooldown_days = max(1, _int_cfg(fcfg, "reengage_cooldown_days", settings.REENGAGE_COOLDOWN_DAYS))
            silent_before = now - timedelta(days=after_days)
            cooldown_before = now - timedelta(days=cooldown_days)

            contacts = (
                await db.execute(
                    select(Contact).where(
                        Contact.tenant_id == tenant.id,
                        Contact.last_inbound_at.is_not(None),
                        Contact.last_inbound_at < silent_before,
                        Contact.crm_stage.in_([
                            CrmStage.NEW_LEAD.value,
                            CrmStage.COLD_LEAD.value,
                            CrmStage.HOT_LEAD.value,
                        ]),
                        Contact.status != ContactStatus.BLOCKED,
                        Contact.ai_paused.is_(False),
                        or_(Contact.last_followup_at.is_(None), Contact.last_followup_at < cooldown_before),
                    ).limit(20)
                )
            ).scalars().all()

            for contact in contacts:
                if not contact.phone:
                    continue
                # 3.3 — ground the message in the real conversation: fetch the
                # last ~10 text-bearing messages (oldest → newest) so Sofia can
                # reference a concrete subject the patient actually raised,
                # instead of a generic nudge. generate_followup_message falls
                # back to the generic wording itself when this is thin/empty.
                recent_messages = (
                    await db.execute(
                        select(Message)
                        .where(
                            Message.tenant_id == tenant.id,
                            Message.contact_id == contact.id,
                            Message.content != "",
                        )
                        .order_by(Message.created_at.desc())
                        .limit(10)
                    )
                ).scalars().all()
                recent_messages = list(reversed(recent_messages))  # oldest → newest

                message = await ai_service.generate_followup_message(
                    tenant, contact, recent_messages=recent_messages
                )
                if not message:
                    continue
                try:
                    await wa_service.send_text_message(instance_token=instance, phone=contact.phone, text=message)
                except Exception:
                    logger.exception("reengagement_send_failed", extra={"contact_id": str(contact.id)})
                    continue
                contact.last_followup_at = now
                await _save_outbound(db, tenant.id, contact.id, message)
                total += 1

        await db.commit()
        if total:
            logger.info("reengagement_sent", extra={"count": total})


async def run_paused_alert() -> None:
    """
    Second-layer alert (item 3.2): catches contacts who were handed off to a
    human (`ai_paused=True`, set by app/services/ai_tools.py::_request_human_handoff)
    and then... nobody answered. If the contact's most recent message is still
    an unanswered INBOUND one and it's older than the stale threshold, email
    the clinic (see app/services/alerts.py::send_handoff_alert_email).

    Runs as its own scheduler job (app/services/scheduler.py), separate from
    run_appointment_reminders/run_reengagement — different trigger condition,
    different cadence (HANDOFF_ALERT_JOB_MINUTES, default every 10 min).

    Episode de-duplication (so this doesn't re-alert every 10 minutes forever):
    `Contact.handoff_alerted_at` records when we last sent this alert. We only
    send again when the contact's latest message is INBOUND and NEWER than
    `handoff_alerted_at` — i.e. the patient wrote again since the last alert
    (or the contact was un-paused and later re-paused with fresh messages),
    which is exactly the signal that a *new* "forgotten" episode has started.
    There is deliberately no separate code path that clears
    `handoff_alerted_at` elsewhere (e.g. on un-pause or on new inbound) — the
    comparison against the latest message's timestamp on every run IS the
    reset logic, so this stays self-contained in this one function.
    """
    now = datetime.now(timezone.utc)

    async with AsyncSessionLocal() as db:
        tenants = (
            await db.execute(select(Tenant).where(Tenant.is_active.is_(True)))
        ).scalars().all()

        total = 0
        for tenant in tenants:
            fcfg = _followups_cfg(tenant)
            if fcfg.get("handoff_alert_email_enabled", True) is False:
                continue

            stale_minutes = max(
                1, _int_cfg(fcfg, "handoff_alert_stale_minutes", settings.HANDOFF_ALERT_STALE_MINUTES)
            )
            stale_before = now - timedelta(minutes=stale_minutes)

            paused_contacts = (
                await db.execute(
                    select(Contact).where(
                        Contact.tenant_id == tenant.id,
                        Contact.ai_paused.is_(True),
                    )
                )
            ).scalars().all()

            for contact in paused_contacts:
                last_msg = (
                    await db.execute(
                        select(Message)
                        .where(Message.tenant_id == tenant.id, Message.contact_id == contact.id)
                        .order_by(Message.created_at.desc())
                        .limit(1)
                    )
                ).scalar_one_or_none()
                # No messages at all, or the last one is OUTBOUND (staff or
                # Sofia already replied) — nothing "forgotten" here.
                if last_msg is None or last_msg.direction != MessageDirection.INBOUND:
                    continue
                if last_msg.created_at > stale_before:
                    continue  # not stale enough yet

                # Already alerted for this exact episode? (no inbound message
                # newer than the last alert means nothing has changed since.)
                if contact.handoff_alerted_at is not None and contact.handoff_alerted_at >= last_msg.created_at:
                    continue

                await send_handoff_alert_email(tenant, contact, reason=None, stale_minutes=stale_minutes)
                contact.handoff_alerted_at = now
                total += 1

        await db.commit()
        if total:
            logger.info("paused_alert_sent", extra={"count": total})
