"""users_email_globally_unique

Revision ID: 4a04df9ac6e7
Revises: 7a2d18eebf33
Create Date: 2026-04-28 20:29:59.877896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '4a04df9ac6e7'
down_revision: Union[str, None] = '7a2d18eebf33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_email', table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    # ### end Alembic commands ###
