"""add_whatsapp_profile_and_ai_paused

Revision ID: a1187bfdff32
Revises: 7ac48e2a60d2
Create Date: 2026-05-03 02:47:06.381487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a1187bfdff32'
down_revision: Union[str, None] = '7ac48e2a60d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('whatsapp_name', sa.String(length=255), nullable=True))
    op.add_column('contacts', sa.Column('profile_picture_url', sa.Text(), nullable=True))
    op.add_column('contacts', sa.Column('ai_paused', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contacts', 'ai_paused')
    op.drop_column('contacts', 'profile_picture_url')
    op.drop_column('contacts', 'whatsapp_name')
    # ### end Alembic commands ###
